# fly.toml app configuration file generated for misty-voice-3876 on 2023-09-24T16:50:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-voice-3876"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
